export const APP_SET_COMPOSITIONS   = 'APP_SET_COMPOSITIONS';
export const APP_ADD_COMPOSITION    = 'APP_ADD_COMPOSITION';
export const APP_DELETE_COMPOSITION = 'APP_DELETE_COMPOSITION';
export const APP_EDIT_COMPOSITION   = 'APP_EDIT_COMPOSITION';

export const APP_CLEAR              = 'APP_CLEAR';
